### ISSUE TITLE
Electric Eyrie repeats 'move' action, instead of showing 'battle' action

### ISSUE THREAD

**Issue by DavidKoot** [Vagabottos/clockroot#17]
I like you app, thanks!
I noticed a bug though. I saw this mainly in the browser on my phone. In the scenario for Electric Eyrie, setup with 'easy', no traits (not sure if this is relevant, but I happen to do this). Then check off setup. Remove the left-most roost from the roost track, set the number of items in the 'bird' column of the decree to two. 
Then Daylight actions show 1. Recruit... (that is correct), 2. Move... (correct too), 3. Move... (wrong!), 4 Place a roost... (correct)
My game went completely wrong, as it turned out that the pacifist birds were invincible :-D 
See also screenshot. Reproduces on android phone with either firefox browser or chrome browser.
I saw this also on a desktop browser in one instance, but I could not reproduce this on another desktop browser.
![Screenshot_20201223-123150](https://user-images.githubusercontent.com/4775747/102993240-13978f80-451d-11eb-913c-d75a5adb03e2.jpg)

**Comment by seiyria** [comment]
Thanks for the detailed report! I'll get a fix up for this today.
